-- Preparing for further API update. Not being used currently
-- Players
wakaba.PLAYER_WAKABA = Isaac.GetPlayerTypeByName("#WAKABA_WAKABA_NAME", false)
wakaba.PLAYER_WAKABA_B = Isaac.GetPlayerTypeByName("#WAKABA_WAKABAB_NAME", true)
wakaba.PLAYER_SHIORI = Isaac.GetPlayerTypeByName("#WAKABA_SHIORI_NAME", false)
wakaba.PLAYER_SHIORI_B = Isaac.GetPlayerTypeByName("#WAKABA_SHIORIB_NAME", true)
wakaba.PLAYER_TSUKASA = Isaac.GetPlayerTypeByName("#WAKABA_TSUKASA_NAME", false)
wakaba.PLAYER_TSUKASA_B = Isaac.GetPlayerTypeByName("#WAKABA_TSUKASAB_NAME", true)

-- Items(normal)

wakaba.COLLECTIBLE_MYSTERIOUS_GAME_CD =  Isaac.GetItemIdByName("#WAKABA_ITEM_MYSTERIOUS_GAME_CD")
wakaba.COLLECTIBLE_WAKABA_DUALITY = Isaac.GetItemIdByName("#WAKABA_ITEM_DUALITY")
wakaba.COLLECTIBLE_D6_PLUS = Isaac.GetItemIdByName("#WAKABA_ITEM_D6_PLUS")
wakaba.COLLECTIBLE_D6_CHAOS = Isaac.GetItemIdByName("#WAKABA_ITEM_D6_CHAOS")
wakaba.COLLECTIBLE_LIL_MOE = Isaac.GetItemIdByName("#WAKABA_ITEM_LIL_MOE")
wakaba.COLLECTIBLE_LIL_SHIVA = Isaac.GetItemIdByName("#WAKABA_ITEM_LIL_SHIVA")
wakaba.COLLECTIBLE_MAIJIMA_MYTHOLOGY = Isaac.GetItemIdByName("#WAKABA_ITEM_MAIJIMA_MYTHOLOGY")
wakaba.COLLECTIBLE_DEJA_VU = Isaac.GetItemIdByName("#WAKABA_ITEM_DEJA_VU")

-- Items(Wakaba)
wakaba.COLLECTIBLE_COUNTER = Isaac.GetItemIdByName("#WAKABA_ITEM_COUNTER")
wakaba.COLLECTIBLE_D_CUP_ICECREAM = Isaac.GetItemIdByName("#WAKABA_ITEM_D_CUP_ICECREAM")
wakaba.COLLECTIBLE_WAKABAS_PENDANT = Isaac.GetItemIdByName("#WAKABA_ITEM_PENDANT") -- Legacy
wakaba.COLLECTIBLE_PENDANT = Isaac.GetItemIdByName("#WAKABA_ITEM_PENDANT")
wakaba.COLLECTIBLE_REVENGE_FRUIT = Isaac.GetItemIdByName("#WAKABA_ITEM_REVENGE_FRUIT")

wakaba.COLLECTIBLE_UNIFORM = Isaac.GetItemIdByName("#WAKABA_ITEM_UNIFORM")

wakaba.COLLECTIBLE_SECRET_CARD = Isaac.GetItemIdByName("#WAKABA_ITEM_SECRET_CARD")

wakaba.COLLECTIBLE_RETURN_POSTAGE = Isaac.GetItemIdByName("#WAKABA_ITEM_RETURN_POSTAGE")
wakaba.COLLECTIBLE_WAKABAS_BLESSING = Isaac.GetItemIdByName("#WAKABA_ITEM_BLESSING") -- Legacy
wakaba.COLLECTIBLE_BLESSING = Isaac.GetItemIdByName("#WAKABA_ITEM_BLESSING")

-- Items(T.Wakaba)

wakaba.COLLECTIBLE_BOOK_OF_FORGOTTEN = Isaac.GetItemIdByName("#WAKABA_ITEM_BOOK_OF_FORGOTTEN")
wakaba.COLLECTIBLE_EATHEART = Isaac.GetItemIdByName("#WAKABA_ITEM_EATHEART")
wakaba.COLLECTIBLE_WAKABAS_NEMESIS = Isaac.GetItemIdByName("#WAKABA_ITEM_NEMESIS") -- Legacy
wakaba.COLLECTIBLE_NEMESIS = Isaac.GetItemIdByName("#WAKABA_ITEM_NEMESIS")

-- Items(Shiori)
wakaba.COLLECTIBLE_BOOK_OF_FOCUS = Isaac.GetItemIdByName("#WAKABA_ITEM_BOOK_OF_FOCUS")
wakaba.COLLECTIBLE_DECK_OF_RUNES = Isaac.GetItemIdByName("#WAKABA_ITEM_BOTTLE_OF_RUNES")
wakaba.COLLECTIBLE_BOTTLE_OF_RUNES = Isaac.GetItemIdByName("#WAKABA_ITEM_BOTTLE_OF_RUNES")
wakaba.COLLECTIBLE_GRIMREAPER_DEFENDER = Isaac.GetItemIdByName("#WAKABA_ITEM_GRIMREAPER_DEFENDER")
wakaba.COLLECTIBLE_BOOK_OF_TRAUMA = Isaac.GetItemIdByName("#WAKABA_ITEM_BOOK_OF_TRAUMA")
wakaba.COLLECTIBLE_BOOK_OF_THE_FALLEN = Isaac.GetItemIdByName("#WAKABA_ITEM_BOOK_OF_THE_FALLEN")
wakaba.COLLECTIBLE_BOOK_OF_THE_GOD = Isaac.GetItemIdByName("#WAKABA_ITEM_BOOK_OF_THE_GOD")
wakaba.COLLECTIBLE_BOOK_OF_SILENCE = Isaac.GetItemIdByName("#WAKABA_ITEM_BOOK_OF_SILENCE")
wakaba.COLLECTIBLE_VINTAGE_THREAT = Isaac.GetItemIdByName("#WAKABA_ITEM_VINTAGE_THREAT")

wakaba.COLLECTIBLE_BOOK_OF_SHIORI = Isaac.GetItemIdByName("#WAKABA_ITEM_BOOK_OF_SHIORI")


-- Items(T.Shiori)

wakaba.COLLECTIBLE_BOOK_OF_CONQUEST = Isaac.GetItemIdByName("#WAKABA_ITEM_BOOK_OF_CONQUEST")
wakaba.COLLECTIBLE_MINERVA_AURA = Isaac.GetItemIdByName("#WAKABA_ITEM_MINERVA_AURA")
wakaba.COLLECTIBLE_MINERVA = Isaac.GetItemIdByName("#WAKABA_ITEM_MINERVA_AURA")

-- Items(Tsukasa)

wakaba.COLLECTIBLE_NASA_LOVER = Isaac.GetItemIdByName("#WAKABA_ITEM_NASA_LOVER")
wakaba.COLLECTIBLE_CONCENTRATION = Isaac.GetItemIdByName("#WAKABA_ITEM_CONCENTRATION")
wakaba.COLLECTIBLE_QUESTION_BLOCK = Isaac.GetItemIdByName("#WAKABA_ITEM_QUESTION_BLOCK")
wakaba.COLLECTIBLE_NEW_YEAR_BOMB = Isaac.GetItemIdByName("#WAKABA_ITEM_NEW_YEAR_EVE_BOMB")
wakaba.COLLECTIBLE_NEW_YEAR_EVE_BOMB = Isaac.GetItemIdByName("#WAKABA_ITEM_NEW_YEAR_EVE_BOMB")
wakaba.COLLECTIBLE_PHANTOM_CLOAK = Isaac.GetItemIdByName("#WAKABA_ITEM_PHANTOM_CLOAK")

wakaba.COLLECTIBLE_LUNAR_STONE = Isaac.GetItemIdByName("#WAKABA_ITEM_LUNAR_STONE")

-- Items(T.Tsukasa)

wakaba.COLLECTIBLE_FLASH_SHIFT = Isaac.GetItemIdByName("#WAKABA_ITEM_FLASH_SHIFT")
wakaba.COLLECTIBLE_ELIXIR_OF_LIFE = Isaac.GetItemIdByName("#WAKABA_ITEM_ELIXIR_OF_LIFE")

-- Items(Challenge)
wakaba.COLLECTIBLE_EYE_OF_CLOCK = Isaac.GetItemIdByName("#WAKABA_ITEM_EYE_OF_CLOCK")
wakaba.COLLECTIBLE_PLUMY = Isaac.GetItemIdByName("#WAKABA_ITEM_PLUMY")
wakaba.COLLECTIBLE_NEKO_FIGURE = Isaac.GetItemIdByName("#WAKABA_ITEM_NEKO_FIGURE")
wakaba.COLLECTIBLE_MICRO_DOPPELGANGER = Isaac.GetItemIdByName("#WAKABA_ITEM_MICRO_DOPPELGANGER")
wakaba.COLLECTIBLE_EXECUTIONER = Isaac.GetItemIdByName("#WAKABA_ITEM_EXECUTIONER")
wakaba.COLLECTIBLE_LIL_WAKABA = Isaac.GetItemIdByName("#WAKABA_ITEM_LIL_WAKABA")
wakaba.COLLECTIBLE_APOLLYON_CRISIS = Isaac.GetItemIdByName("#WAKABA_ITEM_APOLLYON_CRISIS")
wakaba.COLLECTIBLE_ISEKAI_DEFINITION = Isaac.GetItemIdByName("#WAKABA_ITEM_ISEKAI_DEFINITION")
wakaba.COLLECTIBLE_BALANCE = Isaac.GetItemIdByName("#WAKABA_ITEM_BALANCE")
wakaba.COLLECTIBLE_EDEN_STICKY_NOTE = Isaac.GetItemIdByName("#WAKABA_ITEM_EDEN_STICKY_NOTE")
wakaba.COLLECTIBLE_DOUBLE_DREAMS = Isaac.GetItemIdByName("#WAKABA_ITEM_DOUBLE_DREAMS")

-- Trinkets
wakaba.TRINKET_BITCOIN = Isaac.GetTrinketIdByName("#WAKABA_TRINKET_BITCOIN")
wakaba.TRINKET_CLOVER = Isaac.GetTrinketIdByName("#WAKABA_TRINKET_CLOVER")
wakaba.TRINKET_MAGNET_HEAVEN = Isaac.GetTrinketIdByName("#WAKABA_TRINKET_MAGNET_HEAVEN")
wakaba.TRINKET_HARD_BOOK = Isaac.GetTrinketIdByName("#WAKABA_TRINKET_HARD_BOOK")
wakaba.TRINKET_DETERMINATION_RIBBON = Isaac.GetTrinketIdByName("#WAKABA_TRINKET_DETERMINATION_RIBBON")
wakaba.TRINKET_BOOKMARK_BAG = Isaac.GetTrinketIdByName("#WAKABA_TRINKET_BOOKMARK_BAG")
wakaba.TRINKET_RING_OF_JUPITER = Isaac.GetTrinketIdByName("#WAKABA_TRINKET_RING_OF_JUPITER")
wakaba.TRINKET_DIMENSION_CUTTER = Isaac.GetTrinketIdByName("#WAKABA_TRINKET_DIMENSION_CUTTER")
wakaba.TRINKET_DELIMITER = Isaac.GetTrinketIdByName("#WAKABA_TRINKET_DELIMITER")
wakaba.TRINKET_RANGE_OS = Isaac.GetTrinketIdByName("#WAKABA_TRINKET_RANGE_OS")
wakaba.TRINKET_ISAAC_CARTRIDGE = Isaac.GetTrinketIdByName("#WAKABA_TRINKET_ISAAC_CARTRIDGE")

-- Cards

wakaba.CARD_CRANE_CARD = Isaac.GetCardIdByName("#WAKABA_CARD_CRANE_CARD")
wakaba.CARD_CONFESSIONAL_CARD = Isaac.GetCardIdByName("#WAKABA_CARD_CONFESSIONAL_CARD")
wakaba.CARD_BLACK_JOKER = Isaac.GetCardIdByName("#WAKABA_CARD_BLACK_JOKER")
wakaba.CARD_WHITE_JOKER = Isaac.GetCardIdByName("#WAKABA_CARD_WHITE_JOKER")
wakaba.CARD_COLOR_JOKER = Isaac.GetCardIdByName("#WAKABA_CARD_COLOR_JOKER")
wakaba.CARD_DREAM_CARD = Isaac.GetCardIdByName("#WAKABA_CARD_DREAM_CARD")
wakaba.CARD_UNKNOWN_BOOKMARK = Isaac.GetCardIdByName("#WAKABA_CARD_UNKNOWN_BOOKMARK")
wakaba.CARD_QUEEN_OF_SPADES = Isaac.GetCardIdByName("#WAKABA_CARD_QUEEN_OF_SPADES")
wakaba.SOUL_WAKABA = Isaac.GetCardIdByName("#WAKABA_CARD_SOUL_WAKABA")
wakaba.SOUL_SHIORI = Isaac.GetCardIdByName("#WAKABA_CARD_SOUL_SHIORI")
wakaba.SOUL_TSUKASA = Isaac.GetCardIdByName("#WAKABA_CARD_SOUL_TSUKASA")


-- Pills

wakaba.PILL_DAMAGE_MULTIPLIER_UP = Isaac.GetPillEffectByName("#WAKABA_PILL_DAMAGE_MULTIPLIER_UP")
wakaba.PILL_DAMAGE_MULTIPLIER_DOWN = Isaac.GetPillEffectByName("#WAKABA_PILL_DAMAGE_MULTIPLIER_DOWN")
wakaba.PILL_ALL_STATS_UP = Isaac.GetPillEffectByName("#WAKABA_PILL_ALL_STATS_UP")
wakaba.PILL_ALL_STATS_DOWN = Isaac.GetPillEffectByName("#WAKABA_PILL_ALL_STATS_DOWN")
wakaba.PILL_TROLLED = Isaac.GetPillEffectByName("#WAKABA_PILL_TROLLED")
wakaba.PILL_TO_THE_START = Isaac.GetPillEffectByName("#WAKABA_PILL_TO_THE_START")
wakaba.PILL_EXPLOSIVE_DIARRHEA_2 = Isaac.GetPillEffectByName("#WAKABA_PILL_EXPLOSIVE_DIARRHEA_2")
wakaba.PILL_SOCIAL_DISTANCE = Isaac.GetPillEffectByName("#WAKABA_PILL_SOCIAL_DISTANCE")
wakaba.PILL_FLAME_PRINCESS = Isaac.GetPillEffectByName("#WAKABA_PILL_FLAME_PRINCESS")
wakaba.PILL_FIREY_TOUCH = Isaac.GetPillEffectByName("#WAKABA_PILL_FIREY_TOUCH")