return {

	"devilChance",
	"mapChance",
	"luck",
	"xpgain",
	"secretRoomFloorLuck",
	"luckyPennyChance",
	"respecChance",
	"beggarLuck",
	"bossChallengeUnlock",
	"shopSaving",
	"coinDupe",
	"cardFloorLuck",
	"pillFloorLuck",
	"allstatsPerc",

	"hushTimer",
	"bossRushTimer",
	"bossRedChest",
	"bossRushWaves",

	"w_EasterDmg",
	"shieldChance",
	"cloverChestChance",
	"wakabaCloverChestRange",
	"pendantMinLuck",
	"wakabaLeafTear",
	"wakabaFreeClover",
	"wakabaWildCard",
	"wakabaUniformSlot",
	"wakabaIsSmart",

	"unknownBookmarkTears",
	"libraryDamage",
	"libraryReveal",
	"shioriAssistant",

	"tsukasaRaid",
	"tsukasaIntervention",
	"tsukasaMagnetObols",
	"lunarRange",
	"starAllstatsPerc",
	"starReq",
	"lunarProtection",
}