if Encyclopedia then
	local wiki = {
		Wakaba = {
			{ -- Start Data
				{str = "Start Data", fsize = 2, clr = 3, halign = 0},
				{str = "Items", clr = 3, halign = 0},
				{str = "- Wakaba's Blessing"},
				{str = "- Wild Card"},
				{str = "Stats", clr = 3, halign = 0},
				{str = "- HP: 2 Red Hearts"},
				{str = "- Extra: 5 Coins"},
				{str = "- Speed: 1.10"},
				{str = "- Tear Rate: 2.73"},
				{str = "- Damage: 3.50 x1.10"},
				{str = "- Range: 8.00"},
				{str = "- Shot Speed: 0.95"},
				{str = "- Luck: 3.00"},
			},
			{ -- Traits
				{str = "Traits", fsize = 2, clr = 3, halign = 0},
				{str = "Wakaba starts with Homing tears."},
				{str = "Wakaba is unable to find Luck Down and Speed Up pills."},
				{str = "Wakaba can only have 3 hearts total."},
				{str = "Wakaba's Blessing", clr = 3, halign = 0},
				{str = "Guarantees the Devil/Angel Room encountered to be an Angel Room."},
				{str = "- Devil Rooms will no longer appear unless Isaac has Duality, Wakaba's Nemesis, or Black Joker."},
				{str = "Prevents low-quality items from spawning. Greatly increasing quality of items received from all item pools."},
				{str = "- Items with a quality of 0-1 are automatically rerolled."},
				{str = "All penalties by taking damage are removed."},
				{str = "Gives a Holy Mantle Shield when the health is total of 1 heart or low. The shield activates per room until Wakaba recovers her health to more than 1 heart."},
			},
			{ -- Birthright
				{str = "Birthright", fsize = 2, clr = 3, halign = 0},
				{str = "Extends 1 heart limit."},
				{str = "100% chance for angel rooms."},
				{str = "- angel rooms appear even on the floors that not appear normally."},
			},
			{ -- Notes
				{str = "Notes", fsize = 2, clr = 3, halign = 0},
				{str = "Wakaba's Blessing effect for Wakaba is intrinsic to the character, and it can't be rerolled."},
			},
			{ -- Unlockables
				{str = "Unlockables", fsize = 2, clr = 3, halign = 0},
				{str = "- Clover : Defeat Mom's Heart as Wakaba on Hard Mode"},
				{str = "- Counter : Defeat Isaac as Wakaba"},
				{str = "- D-Cup Icecream : Defeat Satan as Wakaba"},
				{str = "- Wakaba's Pendant : Defeat ??? as Wakaba"},
				{str = "- Revenge Fruit : Defeat The Lamb as Wakaba"},
				{str = "- White Joker : Defeat Mega Satan as Wakaba"},
				{str = "- Wakaba's Dream Card : Defeat Boss Rush as Wakaba"},
				{str = "- Color Joker : Defeat Hush as Wakaba"},
				{str = "- Secret Card : Defeat Ultra Greed as Wakaba"},
				{str = "- Crane Card : Defeat Ultra Greedier as Wakaba"},
				{str = "- Wakaba's Uniform : Defeat Delirium as Wakaba"},
				{str = "- Confessional Card : Defeat Mother as Wakaba"},
				{str = "- Return Postage : Defeat The Beast as Wakaba"},
				{str = "- Wakaba's Blessing : Earn all 12 completion Marks on Hard Mode as Wakaba"},
			},
			{ -- Trivia
				{str = "Trivia", fsize = 2, clr = 3, halign = 0},
				{str = "The original character 'Wakaba' is from manga 'Wakaba Girl', from Hara Yui."},
				{str = "In Wakaba Girl, many clover symbols appear in various situations. which makes most of Wakaba's unlockables emphasizes on Luck or Clovers."},
			},
		},
		Shiori = {
			{ -- Start Data
				{str = "Start Data", fsize = 2, clr = 3, halign = 0},
				{str = "Items", clr = 3, halign = 0},
				{str = "- Book of Shiori"},
				{str = "- Books (See traits)"},
				{str = "- Old Capacity"},
				{str = "Stats", clr = 3, halign = 0},
				{str = "- HP: 3 Red Hearts"},
				{str = "- Extra: 12 Keys"},
				{str = "- Speed: 1.00"},
				{str = "- Tear Rate: 3.00"},
				{str = "- Damage: 3.50 x0.5"},
				{str = "- Range: 7.25"},
				{str = "- Shot Speed: 1.00"},
				{str = "- Luck: 0.00"},
			},
			{ -- Traits
				{str = "Traits", fsize = 2, clr = 3, halign = 0},
				{str = "Shiori starts with Horizontal Homing tears."},
				{str = "Shiori can use any book by switching each books."},
				{str = "Modded active items that conut towards Bookworm transformation will also be included."},
				{str = "Following books, Hidden items are blacklisted and are not included."},
				{str = "- Wakaba's Double Dreams"},
				{str = "- Book of The Fallen"},
				{str = "- Maijima Mythology"},
				{str = "- D6 Plus (Unlocked by defeating Isaac as Shiori)"},
				{str = "- Micro Doppelganger (Unlocked by completing Doppelganger challenge)"},
				{str = "- Book of Conquest (Unlocked by defeating Delirium as Tainted Shiori)"},
				{str = "- Isekai Definition (Unlocked by completing Delivery System challenge)"},
				{str = "- Balance ecnalaB (Unlocked by completing Calculation challenge)"},
				{str = "Shiori requires Keys to use active items. This applies for all 3 Active item slots."},
				{str = "Other than following items, Timed and special type charge items can be used normally and do not cost keys."},
				{str = "- Book of Silence"},
				{str = "- Book of Trauma"},
				{str = "- Eraser"},
				{str = "Shiori has a chance to get a Key when room is cleared."},
				{str = "Picking up Batteries as Shiori will give equivalent amount of keys."},
				{str = "- Picking up Micro Battery will give Shiori 1 key."},
				{str = "- Picking up Lil Battery will give Shiori 3 keys."},
				{str = "- Picking up Mega Battery will give Shiori 5 keys."},
				{str = "- Picking up Golden Battery will give Shiori 10 keys."},
				{str = "Shiori cannot see batteries in Shop. All batteries are converted into Golden key for 5 coins."},
				{str = "- Shiori also cannot hold Golden Keys. Obtaining Golden Key automatically converts into 6 keys."},
				{str = "Book of Shiori", clr = 3, halign = 0},
				{str = "Activates additional effect when book active items are being used."},
				{str = "Shiori also gains extra tear effect when book active items are being used."},
				{str = "extra tear effect changes on next book usage."},
			},
			{ -- Birthright
				{str = "Birthright", fsize = 2, clr = 3, halign = 0},
				{str = "Halves key consume when using active item."},
			},
			{ -- Notes
				{str = "Notes", fsize = 2, clr = 3, halign = 0},
				{str = "Book of Shiori effect for Shiori is intrinsic to the character, and it can't be rerolled."},
			},
				{ -- Unlockables
				{str = "Unlockables", fsize = 2, clr = 3, halign = 0},
				{str = "- Hard Book : Defeat Mom's Heart as Shiori on Hard Mode"},
				{str = "- Shiori starts with D6 Plus : Defeat Isaac as Shiori"},
				{str = "- Book of Focus : Defeat Satan as Shiori"},
				{str = "- Rune Archives : Defeat ??? as Shiori"},
				{str = "- Grimreaper Defender : Defeat The Lamb as Shiori"},
				{str = "- Book of the Fallen : Defeat Mega Satan as Shiori"},
				{str = "- Unknown Bookmark : Defeat Boss Rush as Shiori"},
				{str = "- Book of Trauma : Defeat Hush as Shiori"},
				{str = "- Magnet Heaven : Defeat Ultra Greed as Shiori"},
				{str = "- Ribbon of Determination : Defeat Ultra Greedier as Shiori"},
				{str = "- Book of Silence : Defeat Delirium as Shiori"},
				{str = "- Vintage Threat : Defeat Mother as Shiori"},
				{str = "- Book of the God : Defeat The Beast as Shiori"},
				{str = "- Book of Shiori : Earn all 12 completion Marks on Hard Mode as Shiori"},
			},
			{ -- Trivia
				{str = "Trivia", fsize = 2, clr = 3, halign = 0},
				{str = "The original character 'Shiomiya Shiori' is from manga 'The world only god knows'(or 'TWOGK'), from Wakagi Tamaki."},
				{str = "In TWOGK, Shiori was one of the heroines of 'Katsuragi Keima', who has mission to solve the problems of each heroine in order to survive."},
				{str = "The name of the character 'Shiori' has the meaning of 'the bookmark' as japanese, a possible title for the character."},
			},
		},
		Tsukasa = {
			{ -- Start Data
				{str = "Start Data", fsize = 2, clr = 3, halign = 0},
				{str = "Items", clr = 3, halign = 0},
				{str = "- Lunar Stone"},
				{str = "- Concentration"},
				{str = "Stats", clr = 3, halign = 0},
				{str = "- HP: 3 Red Hearts (8 max for containers)"},
				{str = "- Speed: 1.10"},
				{str = "- Tear Rate: 3.93"},
				{str = "- Damage: 3.50 x0.65"},
				{str = "- Range: 6.5"},
				{str = "- Shot Speed: 1.00"},
				{str = "- Luck: 0.00"},
			},
			{ -- Traits
				{str = "Traits", fsize = 2, clr = 3, halign = 0},
				{str = "Tsukasa starts with short range Electric laser."},
				{str = "Lunar Stone", clr = 3, halign = 0},
				{str = "Tsukasa starts with high stats with Lunar powers."},
				{str = "If damage is taken, Lunar Stone deactivates and lunar gauge starts deplete."},
				{str = "- Taking damage further makes lunar gauge deplete speed faster."},
				{str = "- Self damage such as curse room doors does not deplete lunar gauge. if damage is lethal, however, will deplete gauge regardless of source."},
				{str = "Tsukasa dies when Lunar gauge is completely depleted."},
				{str = "Lunar gauge deplete speed can be decreased with current red hearts."},
				{str = "Concentration", clr = 3, halign = 0},
				{str = "Holding Drop button will make Tsukasa concentration mode."},
				{str = "While on concentration mode, she cannot move and takes double damage when hit."},
				{str = "Concentration count is added every time Tsukasa concentrates depending of active's max charge. Finishing this prevent further concentration until room clear."},
				{str = "- This count can be reduced when Tsukasa clears a room."},
				{str = "- Tsukasa cannot concentrate if count is over 60."},
				{str = "Red Hearts and Lunar gauge also can be healed if too low."},
				{str = "Tsukasa cannot move while in concentration. Taking damage in this state will double damage taken."},
				{str = "Isaac Cartridge", clr = 3, halign = 0},
				{str = "Tsukasa only can find pre-rebirth items, and modded items."},
			},
			{ -- Birthright
				{str = "Birthright", fsize = 2, clr = 3, halign = 0},
				{str = "Removes item limitation range."},
				{str = "Increases Lunar gauge capacity, can be overflowed."},
			},
			{ -- Notes
				{str = "Notes", fsize = 2, clr = 3, halign = 0},
				{str = "Lunar Stone, Concentration effect for Tsukasa is intrinsic to the character, and it can't be rerolled."},
			},
			{ -- Unlockables
				{str = "Unlockables", fsize = 2, clr = 3, halign = 0},
				{str = "- Murasame : Defeat Mom's Heart as Tsukasa on Hard Mode"},
				{str = "- Nasa Lover : Defeat Isaac as Tsukasa"},
				{str = "- Beetlejuice : Defeat Satan as Tsukasa"},
				{str = "- Red Corruption : Defeat ??? as Tsukasa"},
				{str = "- Power Bomb : Defeat The Lamb as Tsukasa"},
				{str = "- Plasma Beam : Defeat Mega Satan as Tsukasa"},
				{str = "- Concentration : Defeat Boss Rush as Tsukasa"},
				{str = "- Range OS : Defeat Hush as Tsukasa"},
				{str = "- Arcane Crystal : Defeat Ultra Greed as Tsukasa"},
				{str = "-- Advanced Crystal and Mystic Crystal are also unlocked with Arcane Crystal"},
				{str = "- Question Block : Defeat Ultra Greedier as Tsukasa"},
				{str = "- New Year's Eve Bomb : Defeat Delirium as Tsukasa"},
				{str = "- Phantom Cloak : Defeat Mother as Tsukasa"},
				{str = "- Magma Blade : Defeat The Beast as Tsukasa"},
				{str = "- Lunar Stone : Earn all 12 completion Marks on Hard Mode as Tsukasa"},
			},
			{ -- Trivia
				{str = "Trivia", fsize = 2, clr = 3, halign = 0},
				{str = "The original character 'Yuzaki Tsukasa' is from manga 'Tonikaku Kawaii', from Hata Kenjiro."},
			},
		},
		Richer = {
			{ -- Start Data
				{str = "Start Data", fsize = 2, clr = 3, halign = 0},
				{str = "Items", clr = 3, halign = 0},
				{str = "- Rabbit Ribbon"},
				{str = "- Sweets Catalog"},
				{str = "Stats", clr = 3, halign = 0},
				{str = "- HP: 2 Red, 1 Soul"},
				{str = "- Speed: 1.10"},
				{str = "- Tear Rate: 2.73"},
				{str = "- Damage: 3.50 x1.00"},
				{str = "- Range: 9.00"},
				{str = "- Shot Speed: 1.00"},
				{str = "- Luck: 1.00"},
			},
			{ -- Traits
				{str = "Traits", fsize = 2, clr = 3, halign = 0},
					--{str = ""},
				{str = "Richer takes less damage from most damage sources. (same as the wafer)"},
				{str = "Richer also boosts trinkets by 1."},
				{str = "Rabbit Ribbon", clr = 3, halign = 0},
				{str = "If any curse is applied, replaces it into new curse."},
				{str = "- Curse of Sniper : Replaces Curse of Darkenss, Richer cannot see her weapons, but deal more damage to faraway enemies."},
				{str = "- Curse of Labyrinth : Spawns more Treasure rooms and shops if possible."},
				{str = "- Curse of Fairy : Replaces Curse of the Lost, Richer only can see map in limited range (same as spelunker hat) and her size is smaller."},
				{str = "- Curse of the Magical Girl : Replaces Curse of the Unknown, Soul of the Lost effect is always active, but enemies are weaker. Also allows using Donation mechanics normally."},
				{str = "- Curse of Amensia : Replaces Curse of the Maze, If Richer moves a room, there is a chance to make a random cleared room into uncleared."},
				{str = "- Curse of the Blind : Simply removes the curse."},
				{str = "Stores a charge for active items after every room."},
				{str = "- Rabbit Ribbon can store maximum of 16 charges."},
				{str = "- Automatically consumes stored charges if Isaac's active is not fully charged."},
				{str = "Sweets Catalog", clr = 3, halign = 0},
				{str = "Richer has her expiremental recipies."},
				{str = "When used, Richer gets one of random weapon effects in current room."},
			},
			{ -- Birthright
				{str = "Birthright", fsize = 2, clr = 3, halign = 0},
					--{str = "Richer gets her sweets catalog on her pocket slot."},
				{str = "Sweets Catalog effect is now persistent until next catalog usage."},
				{str = "Curses from Rabbit Ribbon only give advantages."},
				{str = "- Curse of Sniper : deal more damage from faraway enemies."},
				{str = "- Curse of Fairy : activates spelunker hat effect."},
				{str = "- Curse of the Magical Girl : Soul of the Lost effect is always active, but enemies are weaker, and all damage can be taken as normally."},
				{str = "- Curse of Amensia : If Richer moves a room, there is a chance to spawn room clear awards again."},
				{str = ""},
			},
			{ -- Notes
				{str = "Notes", fsize = 2, clr = 3, halign = 0},
				{str = "Rabbit Ribbon effect for Richer is intrinsic to the character, and it can't be rerolled."},
			},
			{ -- Unlockables
				{str = "Unlockables", fsize = 2, clr = 3, halign = 0},
				{str = "- Firefly Lighter : Defeat Mom's Heart as Richer on Hard Mode"},
				{str = "- Sweets Catalog : Defeat Isaac as Richer"},
				{str = "- Anti Balance : Defeat Satan as Richer"},
				{str = "- Double Invader : Defeat ??? as Richer"},
				{str = "- Venom Incantation : Defeat The Lamb as Richer"},
				{str = "- 3D Printer : Defeat Mega Satan as Richer"},
				{str = "- Bunny Parfait : Defeat Boss Rush as Richer"},
				{str = "- Richer's Uniform : Defeat Hush as Richer"},
				{str = "- Clensing Foam : Defeat Ultra Greed as Richer"},
				{str = "- Lil Richer : Defeat Ultra Greedier as Richer"},
				{str = "- Prestige Pass : Defeat Delirium as Richer"},
				{str = "- Cunning Paper : Defeat Mother as Richer"},
				{str = "- Self Burning : Defeat The Beast as Richer"},
				{str = "- Rabbit Ribbon : Earn all 12 completion Marks on Hard Mode as Richer"},
			},
			{ -- Trivia
				{str = "Trivia", fsize = 2, clr = 3, halign = 0},
				{str = "'Richer', or 'riche' is one of doujin characters from Miyasaka Miyu, at Canvas+Garden"},
				{str = "She also appears in a visual novel 'Love's Sweet Garnish'."},
			},
		},
		Rira = {
			{ -- Start Data
				{str = "Start Data", fsize = 2, clr = 3, halign = 0},
				{str = "Items", clr = 3, halign = 0},
				{str = "- Chimaki"},
				{str = "- Nerf Gun"},
				{str = "Stats", clr = 3, halign = 0},
				{str = "- HP: 3 Soul"},
				{str = "- Speed: 1.00 x0.5"},
				{str = "- Tear Rate: 2.73 x3.04"},
				{str = "- Damage: 3.50 x0.16"},
				{str = "- Range: 7.00"},
				{str = "- Shot Speed: 1.05"},
				{str = "- Luck: 0.00"},
			},
			{ -- Traits
				{str = "Traits", fsize = 2, clr = 3, halign = 0},
					--{str = ""},
				{str = ""},
				{str = "Rira has 5% chance to shoot 'aqua' tears that gives aqua properties"},
				{str = "- enemies in aqua state take more damage from laser, explosion, aqua attacks"},
				{str = "- enemies in aqua state take less damage from fire, poison, burning attacks, and red poops"},
				{str = "Rira can use donation mecahnics even while in Lost state."},
				{str = "Chimaki", clr = 3, halign = 0},
				{str = "Rira's soulmate rabbit Chimaki wanders around, but helps her in various ways not limited to:"},
				--{str = "Remove Curses sometimes"},
				--{str = "Make some paid items for free sometimes"},
				{str = "Converts Troll Bombs"},
				{str = "Opens Mega Chest quickly"},
				-- {str = "Opens Challenge room doors"},
				{str = "Commands all blue flies for attack"},
				{str = "Jump towards enemies with Holy Light lasers"},
				{str = "Shoot tears"},
				{str = "Shoot Blue flames to block projectiles"},
				{str = "Nerf Gun", clr = 3, halign = 0},
				{str = "Fires 5 cupid tears which gives weakness properties for 10 seconds."},
			},
			{ -- Birthright
				{str = "Birthright", fsize = 2, clr = 3, halign = 0},
				{str = "Chimaki shoots rainbow lasers instead of tears."},
				{str = "Weakness from Nerf Gun lasts longer."},
			},
			{ -- Notes
				{str = "Notes", fsize = 2, clr = 3, halign = 0},
				{str = "Chimaki effect for Rira is intrinsic to the character, and it can't be rerolled."},
			},
			{ -- Unlockables
				{str = "Unlockables", fsize = 2, clr = 3, halign = 0},
				{str = "- Black Bean Mochi : Defeat Mom's Heart as Rira on Hard Mode"},
				{str = "- Nerf Gun : Defeat Isaac as Rira"},
				{str = "- Rira's Swimsuit : Defeat Satan as Rira"},
				{str = "- Sakura Mont Blanc : Defeat ??? as Rira"},
				{str = "- Chewy Rolly Cake : Defeat The Lamb as Rira"},
				{str = "- Rira's Bento : Defeat Mega Satan as Rira"},
				{str = "- Caramella Pancake : Defeat Boss Rush as Rira"},
				{str = "- Rira's Uniform : Defeat Hush as Rira"},
				{str = "- Rabbit Pillow : Defeat Ultra Greed as Rira"},
				{str = "- Lil Rira : Defeat Ultra Greedier as Rira"},
				{str = "- Rira's Bandage : Defeat Delirium as Rira"},
				{str = "- Sakura Capsule : Defeat Mother as Rira"},
				{str = "- Maid Duet : Defeat The Beast as Rira"},
				{str = "- Chimaki : Earn all 12 completion Marks on Hard Mode as Rira"},
			},
			{ -- Trivia
				{str = "Trivia", fsize = 2, clr = 3, halign = 0},
				{str = "'Rira' is one of doujin characters from Miyasaka Miyu, at Canvas+Garden"},
				{str = "She also appears in a visual novel 'Love's Sweet Garnish'."},
			},
		},
		Anna = {
			{ -- Start Data
				{str = "Start Data", fsize = 2, clr = 3, halign = 0},
				{str = "Items", clr = 3, halign = 0},
				{str = "- Kyoutarou Lover"},
				{str = "Stats", clr = 3, halign = 0},
				{str = "- HP: 3 Red Hearts"},
				{str = "- Speed: 1.00"},
				{str = "- Tear Rate: 2.73"},
				{str = "- Damage: 3.50"},
				{str = "- Range: 6.50"},
				{str = "- Shot Speed: 1.00"},
				{str = "- Luck: 0.00"},
			},
			{ -- Traits
				{str = "Traits", fsize = 2, clr = 3, halign = 0},
					--{str = ""},
				{str = ""},
				{str = "Anna needs to be stable to keep her beauty"},
				{str = "- Any collectible items that not matching Kyoutarou Lover will be rerolled."},
			},
			{ -- Birthright
				{str = "Birthright", fsize = 2, clr = 3, halign = 0},
				{str = "Prevents Quality 0 items from spawning."},
				{str = "+0.003 Speed per obtained collectible"},
			},
			{ -- Notes
				{str = "Notes", fsize = 2, clr = 3, halign = 0},
				{str = "Kyoutarou Lover effect for Anna is intrinsic to the character, and it can't be rerolled."},
			},
			{ -- Trivia
				{str = "Trivia", fsize = 2, clr = 3, halign = 0},
				{str = "'Anna' is one of main characters from 'The Dangers in My Heart'."},
			},
		},
	}
	local wikiTainted = {
		Wakaba = {
			{ -- Start Data
				{str = "Start Data", fsize = 2, clr = 3, halign = 0},
				{str = "Items", clr = 3, halign = 0},
				{str = "- Wakaba's Nemesis"},
				{str = "- Eat Heart"},
				{str = "Stats", clr = 3, halign = 0},
				{str = "- HP: 3 Black Hearts"},
				{str = "- Extra: 2 Bombs"},
				{str = "- Speed: 1.25"},
				{str = "- Tear Rate: 5.71"},
				{str = "- Damage: 2.45"},
				{str = "- Range: 5.00"},
				{str = "- Shot Speed: 0.80"},
				{str = "- Luck: -5.00"},
			},
			{ -- Traits
				{str = "Traits", fsize = 2, clr = 3, halign = 0},
				{str = "Tainted Wakaba starts with Piercing tears."},
				{str = "Tainted Wakaba is unable to find Luck Up pills."},
				{str = "All Heart Containers are converted into Black Hearts."},
				{str = "Worst Items, Furious Destiny - Wakaba's Nemesis", clr = 3, halign = 0},
				{str = "Tainted Wakaba cannot find 4 quality items."},
				{str = "Tainted Wakaba has reduced chance to find 3 quality items."},
				{str = "All collectibles give Tainted Wakaba +3.6 temporary damage up, and small permanent all stat downs."},
				{str = "Guarentees the Devil/Angel Room encountered to be an Devil Room."},
				{str = "All collectibles on sale requires soul hearts."},
				{str = "All penalties by taking damage are removed."},
			},
			{ -- Birthright
				{str = "Birthright", fsize = 2, clr = 3, halign = 0},
				{str = "Immune to all explosions and shockwaves."},
				{str = "Reduce Temporary damage reduction rate."},
			},
			{ -- Notes
				{str = "Notes", fsize = 2, clr = 3, halign = 0},
				{str = "Wakaba's Nemesis effect for Tainted Wakaba is intrinsic to the character, and it can't be rerolled."},
			},
			{ -- Unlockables
				{str = "Unlockables", fsize = 2, clr = 3, halign = 0},
				{str = "- Book of Forgotten : Defeat Isaac, Satan, ???, The Lamb as Tainted Wakaba"},
				{str = "- Clover Chest : Defeat Mega Satan as Tainted Wakaba"},
				{str = "- Soul of Wakaba : Defeat Boss Rush, Hush as Tainted Wakaba"},
				{str = "- Black Joker : Defeat Ultra Greedier as Tainted Wakaba"},
				{str = "- Eat Heart : Defeat Delirium as Tainted Wakaba"},
				{str = "- Bitcoin II : Defeat Mother as Tainted Wakaba"},
				{str = "- Wakaba's Nemesis : Defeat The Beast as Tainted Wakaba"},
			},
		},
		Shiori = {
			{ -- Start Data
				{str = "Start Data", fsize = 2, clr = 3, halign = 0},
				{str = "Items", clr = 3, halign = 0},
				{str = "- Book of Shiori"},
				{str = "- Book of Conquest"},
				{str = "- Minerva's Aura"},
				{str = "- Old Capacity"},
				{str = "Stats", clr = 3, halign = 0},
				{str = "- HP: 3 Soul Hearts"},
				{str = "- Extra: 12 Keys"},
				{str = "- Speed: 1.00"},
				{str = "- Tear Rate: 3.00"},
				{str = "- Damage: 1.00"},
				{str = "- Range: 6.00"},
				{str = "- Shot Speed: 1.00"},
				{str = "- Luck: 0.00"},
			},
			{ -- Traits
				{str = "Traits", fsize = 2, clr = 3, halign = 0},
				{str = "All Heart Containers are converted into Soul Hearts."},
				{str = "Tainted Shiori requires Keys to use active items. This applies for all 3 Active item slots."},
				{str = "Tainted Shiori has a chance to get the Key when room clears."},
				{str = "Picking up Batteries as Tainted Shiori will give equivalent amount of Keys."},
				{str = "- Picking up Micro Battery will give Tainted Shiori 1 Key."},
				{str = "- Picking up Lil Battery will give Tainted Shiori 3 Keys."},
				{str = "- Picking up Mega Battery will give Tainted Shiori 5 Keys."},
				{str = "- Picking up Golden Battery will give Tainted Shiori 10 Keys."},
				{str = "Tainted Shiori cannot see batteries in Shop. All batteries are converted into Golden key for 5 coins."},
				{str = "- Tainted Shiori also cannot hold Golden Keys. Obtaining Golden Key automatically converts into 6 keys."},
				{str = "Jupiter Wings", clr = 3, halign = 0},
				{str = "Tainted Shiori starts with flight."},
				{str = "Book of Shiori", clr = 3, halign = 0},
				{str = "Activates additional effect when book active items are being used."},
				{str = "Shiori also gains extra tear effect when book active items are being used."},
				{str = "extra tear effect changes on next book usage."},
				{str = "Minerva's Aura", clr = 3, halign = 0},
				{str = "Emits aura that follows Tainted Shiori."},
				{str = "Friendly monsters inside the aura gradually recovers health."},
				{str = "- Friendly monsters can recover up to 2x of their max health."},
				{str = "While Other players stand inside the aura, grants + 1.5 damage up, + 2.0 tears up, +1.5 range up and homing tears. It also gives players a chance to block damage similar to Infamy."},
			},
			{ -- Birthright
				{str = "Birthright", fsize = 2, clr = 3, halign = 0},
				{str = "Allows getting aura bonus for herself"},
				{str = "Reduces key consume by 1 when using active item. (Minimum 1)"},
				{str = "The number of required keys for Book of Conquest is reduced. (Minimum 1)"},
				{str = "All stats up for current number of conquered enemies."},
				{str = "- Also applies for other players inside Minerva's Aura."},
				{str = "Faster health regen rate of Minerva's aura for conquered enemies."},
			},
			{ -- Notes
				{str = "Notes", fsize = 2, clr = 3, halign = 0},
				{str = "Book of Shiori and Minerva's Aura effect for Tainted Shiori is intrinsic to the character, and it can't be rerolled."},
				{str = "- Tainted Shiori cannot get aura bonus even when she stands inside her own aura."},
				{str = "- Obtaining Birthright will allow Tainted Shiori get aura bonus for her own aura."},
				{str = "- Tainted Shiori can still find this item on a pedestal. Picking the item increases further aura bonuses."},
			},
			{ -- Unlockables
				{str = "Unlockables", fsize = 2, clr = 3, halign = 0},
				{str = "- Bookmark Bag : Defeat Isaac, Satan, ???, The Lamb as Tainted Shiori"},
				{str = "- Another Fortune Machine : Defeat Mega Satan as Tainted Shiori"},
				{str = "- Soul of Shiori : Defeat Boss Rush, Hush as Tainted Shiori"},
				{str = "- Queen of Spades : Defeat Ultra Greedier as Tainted Shiori"},
				{str = "- Book of Conquest : Defeat Delirium as Tainted Shiori"},
				{str = "- Ring of Jupiter : Defeat Mother as Tainted Shiori"},
				{str = "- Minerva's Aura : Defeat The Beast as Tainted Shiori"},
			},
			{ -- Trivia
				{str = "Trivia", fsize = 2, clr = 3, halign = 0},
				{str = "The original character 'Shiomiya Shiori' is from manga 'The world only god knows'(or 'TWOGK'), from Wakagi Tamaki."},
				{str = "In TWOGK, Shiori was one of the heroines of 'Katsuragi Keima', who has mission to solve the problems of each heroine in order to survive."},
				{str = "Shiori was also one of six heroines who holds the Goddesses called 'Sisters of Jupiter'."},
				{str = "The Goddess who is held by Shiori is 'Minerva', a possible title for the character."},
			},
		},
		Tsukasa = {
			{ -- Start Data
				{str = "Start Data", fsize = 2, clr = 3, halign = 0},
				{str = "Items", clr = 3, halign = 0},
				{str = "- Elixir of life"},
				{str = "- Flash Shift (Passive)"},
				{str = "- Murasame (Passive)"},
				{str = "Stats", clr = 3, halign = 0},
				{str = "- HP: 3 Red Hearts"},
				{str = "- Speed: 1.20"},
				{str = "- Tear Rate: 1.88 / Blindfolded"},
				{str = "- Damage: 2.28"},
				{str = "- Range: 6.50"},
				{str = "- Shot Speed: 1.00"},
				{str = "- Luck: 0.00"},
			},
			{ -- Traits
				{str = "Traits", fsize = 2, clr = 3, halign = 0},
				{str = "No Tears", clr = 3, halign = 0},
				{str = "Tainted Tsukasa cannot shoot tears, making Flash Shift only attack method for her initial state."},
				{str = "Brittle Immortal", clr = 3, halign = 0},
				{str = "Tainted Tsukasa does not have any invincibiliy frames, Getting constant hit will take a lot of health."},
				{str = "Tainted Tsukasa automatically heals her health if no damage is taken for breif time."},
				{str = "Tainted Tsukasa cannot get Soul Hearts. All soul hearts are converted into Bone Hearts."},
				{str = "Flash Shift / Murasame", clr = 3, halign = 0},
				{str = "Flash Shift + Murasame is the only attack method for Tainted Tsukasa."},
				{str = "Pressing attack button will make Tsukasa dash for short distance in firing direction."},
				{str = "Tsukasa can only use Flash Shift 3 times. After using 3 times, Tsukasa needs to wait some times to make available again. Cooldown speed scales with Tears stat."},
				{str = "Using Flash Shift will grant Tsukasa 20 invincibility frames."},
			},
			{ -- Birthright
				{str = "Birthright", fsize = 2, clr = 3, halign = 0},
				{str = "Allows Tainted Tsukasa to shoot tears."},
				{str = "Flash Shift ability is now moved into pocket item slot."},
			},
			{ -- Notes
				{str = "Notes", fsize = 2, clr = 3, halign = 0},
				{str = "Elixir of life, Murasame, Flash Shift effect for Tainted Tsukasa is intrinsic to the character, and it can't be rerolled."},
			},
			{ -- Unlockables
				{str = "Unlockables", fsize = 2, clr = 3, halign = 0},
				{str = "- Isaac Cartridge : Defeat Isaac, Satan, ???, The Lamb as Tainted Tsukasa"},
				{str = "-- Afterbirth/Repentance Cartridge are also unlocked with Isaac Cartridge"},
				{str = "- Easter Coin : Defeat Mega Satan as Tainted Tsukasa"},
				{str = "- Soul of Tsukasa : Defeat Boss Rush, Hush as Tainted Tsukasa"},
				{str = "- Return Token : Defeat Ultra Greedier as Tainted Tsukasa"},
				{str = "- Flash Shift : Defeat Delirium as Tainted Tsukasa"},
				{str = "- Siren's Badge : Defeat Mother as Tainted Tsukasa"},
				{str = "- Elixir of life : Defeat The Beast as Tainted Tsukasa"},
			},
			{ -- Trivia
				{str = "Trivia", fsize = 2, clr = 3, halign = 0},
				{str = "The original character 'Iwasaka --------' is from manga 'FLY ME TO THE MOON', from Hata Kenjiro."},
				{str = "Tsukasa herself did not want Elixir of Life, but his father fed her the potion This later caused massive genocide for her family. Tsukasa later was captured, but slain people who believed the flesh of Tsukasa might give them long life."},
				{str = "The true name of tsukasa is unknown. The name 'Tsukasa' is given by a stranger called 'Umaya', who later became prince Shotoku."},
				{str = "After being immortal, Shotoku asked her to watch his history, with his challenge for humanity reaching the moon."},
			},
		},
		Richer = {
			{ -- Start Data
				{str = "Start Data", fsize = 2, clr = 3, halign = 0},
				{str = "Items", clr = 3, halign = 0},
				{str = "- Rabbit Ribbon"},
				{str = "- The Winter Albireo"},
				{str = "- Water-Flame"},
				{str = "Stats", clr = 3, halign = 0},
				{str = "- HP: 3 Soul Hearts"},
				{str = "- Extra: 2 Keys"},
				{str = "- Speed: 1.08"},
				{str = "- Tear Rate: 3.33"},
				{str = "- Damage: 2.63"},
				{str = "- Range: 6.50"},
				{str = "- Shot Speed: 0.90"},
				{str = "- Luck: 0.00"},
			},
			{ -- Traits
				{str = "Traits", fsize = 2, clr = 3, halign = 0},
				{str = "All Heart Containers are converted into Soul Hearts."},
				{str = "Curse of Flames", clr = 3, halign = 0},
				{str = "Tainted Richer cannot obtain items for normal method. Touching the collectible as Tainted Richer will convert into Item Wisp."},
				{str = "Actives can be obtained through normal ways."},
				{str = "Plot-critical items, Death Certificate items, Genesis room items are immune to this effect, thus can be obtained normally."},
				{str = "The Winter Albireo", clr = 3, halign = 0},
				{str = "If possible, her own version of rabbey-planetarium appears."},
				{str = "Rabbey-planetarium contains a planetarium item in even floors, and normal treasure item in odd floors."},
				{str = "- Rabbey-planetariums continue appear in Womb/Corpse floors."},
				{str = "- Rabbey-planetariums contain Devil items in Sheol, Angel items in Cathedral."},
				{str = "- Rabbey-planetariums contain Secret room items in Blue Womb."},
				{str = "- Rabbey-planetariums replace Treasure rooms if playing as Tainted Richer."},
				{str = "Water-Flame", clr = 3, halign = 0},
				{str = "Her magical body allows absorbing the item wisps."},
				{str = "Tainted Richer can select which wisp to absorb into passive item."},
			},
			{ -- Birthright
				{str = "Birthright", fsize = 2, clr = 3, halign = 0},
				{str = "Converted item wisps will be doubled."},
				{str = "Converted items will be doubled."},
			},
			{ -- Notes
				{str = "Notes", fsize = 2, clr = 3, halign = 0},
				{str = "Rabbit Ribbon, The Winter Albireo for Tainted Richer is intrinsic to the character, and it can't be rerolled."},
			},
			{ -- Unlockables
				{str = "Unlockables", fsize = 2, clr = 3, halign = 0},
				{str = "- Star Reversal : Defeat Isaac, Satan, ???, The Lamb as Tainted Richer"},
				{str = "- Crystal Restock machine: Defeat Mega Satan as Tainted Richer"},
				{str = "- Soul of Richer : Defeat Boss Rush, Hush as Tainted Richer"},
				{str = "- Trial Stew : Defeat Ultra Greedier as Tainted Richer"},
				{str = "- Water-Flame : Defeat Delirium as Tainted Richer"},
				{str = "- Eternity Cookie : Defeat Mother as Tainted Richer"},
				{str = "- The Winter Albireo : Defeat The Beast as Tainted Richer"},
			},
		},
		Rira = {
			{ -- Start Data
				{str = "Start Data", fsize = 2, clr = 3, halign = 0},
				{str = "Items", clr = 3, halign = 0},
				{str = "- Azure Rir"},
				{str = "- Rabbey Ward"},
				{str = "Stats", clr = 3, halign = 0},
				{str = "- HP: 3 Soul Hearts"},
				{str = "- Speed: 1.00"},
				{str = "- Tear Rate: 2.73"},
				{str = "- Damage: 3.50"},
				{str = "- Range: 6.50"},
				{str = "- Shot Speed: 1.00"},
				{str = "- Luck: 0.00"},
			},
			{ -- Traits
				{str = "Traits", fsize = 2, clr = 3, halign = 0},
				{str = "All Heart Containers are converted into Soul Hearts."},
				{str = "Ecchi Aqua", clr = 3, halign = 0},
				{str = "Tainted Rira cannot see items in Treasure rooms."},
				{str = "All treasure room items are converted into Aqua Trinkets."},
				{str = "Plot-critical items, Death Certificate items, Genesis room items are immune to this effect, thus can be obtained normally."},
				{str = "Azure Rir", clr = 3, halign = 0},
				{str = "All trinkets are Aqua Trinkets."},
				{str = "- This ignores unlock status."},
				{str = "Rabbey Ward", clr = 3, halign = 0},
				{str = "Her soulmate Chimaki now become her supporter, revealing nearby rooms."},
				{str = "Clearing rooms within Rabbey Ward gives Tainted Rira Soul Heart."},
				{str = "Rooms within Rabbey Ward gives Tainted Rira Tears, Damage bonus."},
				{str = "Tainted Rira's health slowly drains outside of rooms nearby Rabbey Ward."},
			},
			{ -- Birthright
				{str = "Birthright", fsize = 2, clr = 3, halign = 0},
				{str = "Health no longer drains outside of ward area."},
				{str = "Doubles Rabbey Ward charge rate for new room."},
				{str = "Using Rabbey Ward also divides nearby pedestal in the room."},
				{str = "Rabbey Wards shoot homing laser to enemies."},
			},
			{ -- Notes
				{str = "Notes", fsize = 2, clr = 3, halign = 0},
				{str = "Azure Rir for Tainted Rira is intrinsic to the character, and it can't be rerolled."},
			},
			{ -- Unlockables
				{str = "Unlockables", fsize = 2, clr = 3, halign = 0},
				{str = "- Caramella Candy Bag : Defeat Isaac, Satan, ???, The Lamb as Tainted Rira"},
				{str = "- Aqua Trinkets: Defeat Mega Satan as Tainted Rira"},
				{str = "- Soul of Rira : Defeat Boss Rush, Hush as Tainted Rira"},
				{str = "- Flip Card : Defeat Ultra Greedier as Tainted Rira"},
				{str = "- Rabbey Ward : Defeat Delirium as Tainted Rira"},
				{str = "- Pink Fork : Defeat Mother as Tainted Rira"},
				{str = "- Azure Rir : Defeat The Beast as Tainted Rira"},
			},
		},
	}
	local wikiTarnished = {
		Wakaba = {

		},
		Shiori = {

		},
		Tsukasa = {

		},
		Richer = {

		},
		Rira = {

		},
	}



	local entries = {
		[wakaba.Enums.Players.WAKABA] = {
			Name = "Wakaba",
			Description = "The Clover",
			Sprite = Encyclopedia.RegisterSprite(wakaba.modpath .. "content/gfx/characterportraits.anm2", "Wakaba", 0),
			CompletionTrackerFuncs = { function() return wakaba:GetEncyPaper(wakaba.Enums.Players.WAKABA) end },
		},
		[wakaba.Enums.Players.SHIORI] = {
			Name = "Shiori",
			Description = "The Bookmark",
			Sprite = Encyclopedia.RegisterSprite(wakaba.modpath .. "content/gfx/characterportraits.anm2", "Shiori", 0),
			CompletionTrackerFuncs = { function() return wakaba:GetEncyPaper(wakaba.Enums.Players.SHIORI) end },
		},
		[wakaba.Enums.Players.TSUKASA] = {
			Name = "Tsukasa",
			Description = "The Entertainer",
			Sprite = Encyclopedia.RegisterSprite(wakaba.modpath .. "content/gfx/characterportraits.anm2", "Tsukasa", 0),
			CompletionTrackerFuncs = { function() return wakaba:GetEncyPaper(wakaba.Enums.Players.TSUKASA) end },
		},
		[wakaba.Enums.Players.RICHER] = {
			Name = "Richer",
			Description = "The Maid",
			Sprite = Encyclopedia.RegisterSprite(wakaba.modpath .. "content/gfx/characterportraits.anm2", "Richer", 0),
			CompletionTrackerFuncs = { function() return wakaba:GetEncyPaper(wakaba.Enums.Players.RICHER) end },
		},
		[wakaba.Enums.Players.RIRA] = {
			Name = "Rira",
			Description = "The Curity",
			Sprite = Encyclopedia.RegisterSprite(wakaba.modpath .. "content/gfx/characterportraits.anm2", "Rira", 0),
			CompletionTrackerFuncs = { function() return wakaba:GetEncyPaper(wakaba.Enums.Players.RIRA) end },
		},
		[wakaba.Enums.Players.ANNA] = {
			Name = "Anna",
			Description = "The Harmony",
			Sprite = Encyclopedia.RegisterSprite(wakaba.modpath .. "content/gfx/characterportraits.anm2", "Anna", 0),
		},
		[wakaba.Enums.Players.WAKABA_B] = {
			Tainted = true,
			Name = "Wakaba",
			Description = "The Fury",
			Sprite = Encyclopedia.RegisterSprite(wakaba.modpath .. "content/gfx/characterportraitsalt.anm2", "WakabaB", 0),
			CompletionTrackerFuncs = { function() return wakaba:GetEncyPaper(wakaba.Enums.Players.WAKABA_B) end },
		},
		[wakaba.Enums.Players.SHIORI_B] = {
			Tainted = true,
			Name = "Shiori",
			Description = "The Minerva",
			Sprite = Encyclopedia.RegisterSprite(wakaba.modpath .. "content/gfx/characterportraitsalt.anm2", "ShioriB", 0),
			CompletionTrackerFuncs = { function() return wakaba:GetEncyPaper(wakaba.Enums.Players.SHIORI_B) end },
		},
		[wakaba.Enums.Players.TSUKASA_B] = {
			Tainted = true,
			Name = "Tsukasa",
			Description = "The Phoenix",
			Sprite = Encyclopedia.RegisterSprite(wakaba.modpath .. "content/gfx/characterportraitsalt.anm2", "TsukasaB",0),
			UnlockFunc = function(self) -- Again this is in case your tainted is "unlockable"
				if not wakaba.state.options.allowlockeditems and not wakaba.state.unlock.taintedtsukasa then
					self.Spr = Encyclopedia.RegisterSprite(wakaba.modpath .. "content/gfx/characterportraitsalt.anm2", "TsukasaB",1)
					self.Desc = "Use Red Key on the hidden door in the Final Chapter as Tsukasa."
					self.TargetColor = Encyclopedia.VanillaColor

					return self
				end
			end,
			CompletionTrackerFuncs = { function() return wakaba:GetEncyPaper(wakaba.Enums.Players.TSUKASA_B) end },
		},
		[wakaba.Enums.Players.RICHER_B] = {
			Tainted = true,
			Name = "Richer",
			Description = "The Miko",
			Sprite = Encyclopedia.RegisterSprite(wakaba.modpath .. "content/gfx/characterportraitsalt.anm2", "RicherB", 0),
			UnlockFunc = function(self) -- Again this is in case your tainted is "unlockable"
				if not wakaba.state.options.allowlockeditems and not wakaba.state.unlock.taintedricher then
					self.Spr = Encyclopedia.RegisterSprite(wakaba.modpath .. "content/gfx/characterportraitsalt.anm2", "RicherB",1)
					self.Desc = "Use Red Key on the hidden door in the Final Chapter as Richer."
					self.TargetColor = Encyclopedia.VanillaColor

					return self
				end
			end,
			CompletionTrackerFuncs = { function() return wakaba:GetEncyPaper(wakaba.Enums.Players.RICHER_B) end },
		},
		[wakaba.Enums.Players.RIRA_B] = {
			Tainted = true,
			Name = "Rira",
			Description = "The Aqua",
			Sprite = Encyclopedia.RegisterSprite(wakaba.modpath .. "content/gfx/characterportraitsalt.anm2", "RiraB", 0),
			UnlockFunc = function(self) -- Again this is in case your tainted is "unlockable"
				if not wakaba.state.options.allowlockeditems and not wakaba.state.unlock.taintedrira then
					self.Spr = Encyclopedia.RegisterSprite(wakaba.modpath .. "content/gfx/characterportraitsalt.anm2", "RiraB",1)
					self.Desc = "Use Red Key on the hidden door in the Final Chapter as Rira."
					self.TargetColor = Encyclopedia.VanillaColor

					return self
				end
			end,
			CompletionTrackerFuncs = { function() return wakaba:GetEncyPaper(wakaba.Enums.Players.RIRA_B) end },
		},
		[wakaba.Enums.Players.WAKABA_T] = {
			Tarnished = true,
			Hide = true,
			Name = "Wakaba",
			Description = "The Root",
			Sprite = Encyclopedia.RegisterSprite(wakaba.modpath .. "content/gfx/characterportraitsalt.anm2", "RicherB", 0),
		},
		[wakaba.Enums.Players.SHIORI_T] = {
			Tarnished = true,
			Hide = true,
			Name = "Shiori",
			Description = "The Page",
			Sprite = Encyclopedia.RegisterSprite(wakaba.modpath .. "content/gfx/characterportraitsalt.anm2", "RicherB", 0),
		},
		[wakaba.Enums.Players.TSUKASA_T] = {
			Tarnished = true,
			Hide = true,
			Name = "Tsukasa",
			Description = "The Loop",
			Sprite = Encyclopedia.RegisterSprite(wakaba.modpath .. "content/gfx/characterportraitsalt.anm2", "RicherB", 0),
		},
		[wakaba.Enums.Players.RICHER_T] = {
			Tarnished = true,
			Hide = true,
			Name = "Richer",
			Description = "The Solar",
			Sprite = Encyclopedia.RegisterSprite(wakaba.modpath .. "content/gfx/characterportraitsalt.anm2", "RicherB", 0),
		},
		[wakaba.Enums.Players.RIRA_T] = {
			Tarnished = true,
			Hide = true,
			Name = "Rira",
			Description = "The Aqua",
			Sprite = Encyclopedia.RegisterSprite(wakaba.modpath .. "content/gfx/characterportraitsalt.anm2", "RicherB", 0),
		},
	}

	wakaba.encyclopediadesc.desc.characters = entries

	for _, playerType in ipairs(wakaba.encyclopediadesc.desc.char_sorted_keys) do
		local desc = wakaba.encyclopediadesc.desc.characters[playerType]
		if desc and desc.Tainted then
			Encyclopedia.AddCharacterTainted({
				Hide = desc.Hide,
				ModName = wakaba.encyclopediadesc.class,
				Class = wakaba.encyclopediadesc.class,
				ID = playerType,
				Name = desc.Name,
				Description = desc.Description,
				Sprite = desc.Sprite,
				CompletionTrackerFuncs = desc.CompletionTrackerFuncs,
				UnlockFunc = desc.UnlockFunc,
				WikiDesc = wikiTainted[desc.Name],
			})
		elseif desc and desc.Tarnished then
			Encyclopedia.AddCharacterTainted({
				Hide = desc.Hide,
				ModName = wakaba.encyclopediadesc.class,
				Class = wakaba.encyclopediadesc.class,
				ID = playerType,
				Name = desc.Name,
				Description = desc.Description,
				Sprite = desc.Sprite,
				CompletionTrackerFuncs = desc.CompletionTrackerFuncs,
				UnlockFunc = desc.UnlockFunc,
				WikiDesc = wikiTarnished[Name],
			})
		elseif desc then
			Encyclopedia.AddCharacter({
				Hide = desc.Hide,
				ModName = wakaba.encyclopediadesc.class,
				Class = wakaba.encyclopediadesc.class,
				ID = playerType,
				Name = desc.Name,
				Description = desc.Description,
				Sprite = desc.Sprite,
				CompletionTrackerFuncs = desc.CompletionTrackerFuncs,
				WikiDesc = wiki[desc.Name],
			})
		end
	end
end