
-- Cards

wakaba.CARD_CRANE_CARD = Isaac.GetCardIdByName("#WAKABA_CARD_CRANE_CARD")
wakaba.CARD_CONFESSIONAL_CARD = Isaac.GetCardIdByName("#WAKABA_CARD_CONFESSIONAL_CARD")
wakaba.CARD_BLACK_JOKER = Isaac.GetCardIdByName("#WAKABA_CARD_BLACK_JOKER")
wakaba.CARD_WHITE_JOKER = Isaac.GetCardIdByName("#WAKABA_CARD_WHITE_JOKER")
wakaba.CARD_COLOR_JOKER = Isaac.GetCardIdByName("#WAKABA_CARD_COLOR_JOKER")
wakaba.CARD_DREAM_CARD = Isaac.GetCardIdByName("#WAKABA_CARD_DREAM_CARD")
wakaba.CARD_UNKNOWN_BOOKMARK = Isaac.GetCardIdByName("#WAKABA_CARD_UNKNOWN_BOOKMARK")
wakaba.CARD_QUEEN_OF_SPADES = Isaac.GetCardIdByName("#WAKABA_CARD_QUEEN_OF_SPADES")
wakaba.CARD_OLD_CARD = Isaac.GetCardIdByName("#WAKABA_CARD_OLD_CARD")
wakaba.SOUL_WAKABA = Isaac.GetCardIdByName("#WAKABA_CARD_SOUL_WAKABA")
wakaba.SOUL_SHIORI = Isaac.GetCardIdByName("#WAKABA_CARD_SOUL_SHIORI")
wakaba.SOUL_TSUKASA = Isaac.GetCardIdByName("#WAKABA_CARD_SOUL_TSUKASA")


-- Pills

wakaba.PILL_DAMAGE_MULTIPLIER_UP = Isaac.GetPillEffectByName("#WAKABA_PILL_DAMAGE_MULTIPLIER_UP")
wakaba.PILL_DAMAGE_MULTIPLIER_DOWN = Isaac.GetPillEffectByName("#WAKABA_PILL_DAMAGE_MULTIPLIER_DOWN")
wakaba.PILL_ALL_STATS_UP = Isaac.GetPillEffectByName("#WAKABA_PILL_ALL_STATS_UP")
wakaba.PILL_ALL_STATS_DOWN = Isaac.GetPillEffectByName("#WAKABA_PILL_ALL_STATS_DOWN")
wakaba.PILL_TROLLED = Isaac.GetPillEffectByName("#WAKABA_PILL_TROLLED")
wakaba.PILL_TO_THE_START = Isaac.GetPillEffectByName("#WAKABA_PILL_TO_THE_START")
wakaba.PILL_EXPLOSIVE_DIARRHEA_2 = Isaac.GetPillEffectByName("#WAKABA_PILL_EXPLOSIVE_DIARRHEA_2")
wakaba.PILL_SOCIAL_DISTANCE = Isaac.GetPillEffectByName("#WAKABA_PILL_SOCIAL_DISTANCE")
wakaba.PILL_FLAME_PRINCESS = Isaac.GetPillEffectByName("#WAKABA_PILL_FLAME_PRINCESS")
wakaba.PILL_FIREY_TOUCH = Isaac.GetPillEffectByName("#WAKABA_PILL_FIREY_TOUCH")