
-- Items(normal)

wakaba.COLLECTIBLE_MYSTERIOUS_GAME_CD =  Isaac.GetItemIdByName("#WAKABA_ITEM_MYSTERIOUS_GAME_CD")
wakaba.COLLECTIBLE_WAKABA_DUALITY = Isaac.GetItemIdByName("#WAKABA_ITEM_DUALITY")
wakaba.COLLECTIBLE_D6_PLUS = Isaac.GetItemIdByName("#WAKABA_ITEM_D6_PLUS")
wakaba.COLLECTIBLE_D6_CHAOS = Isaac.GetItemIdByName("#WAKABA_ITEM_D6_CHAOS")
wakaba.COLLECTIBLE_LIL_MOE = Isaac.GetItemIdByName("#WAKABA_ITEM_LIL_MOE")
wakaba.COLLECTIBLE_LIL_SHIVA = Isaac.GetItemIdByName("#WAKABA_ITEM_LIL_SHIVA")
wakaba.COLLECTIBLE_MAIJIMA_MYTHOLOGY = Isaac.GetItemIdByName("#WAKABA_ITEM_MAIJIMA_MYTHOLOGY")
wakaba.COLLECTIBLE_DEJA_VU = Isaac.GetItemIdByName("#WAKABA_ITEM_DEJA_VU")
wakaba.COLLECTIBLE_MOE_MUFFIN = Isaac.GetItemIdByName("#WAKABA_MOE_MUFFIN")

-- Items(Wakaba)
wakaba.COLLECTIBLE_COUNTER = Isaac.GetItemIdByName("#WAKABA_ITEM_COUNTER")
wakaba.COLLECTIBLE_D_CUP_ICECREAM = Isaac.GetItemIdByName("#WAKABA_ITEM_D_CUP_ICECREAM")
wakaba.COLLECTIBLE_WAKABAS_PENDANT = Isaac.GetItemIdByName("#WAKABA_ITEM_PENDANT") -- Legacy
wakaba.COLLECTIBLE_PENDANT = Isaac.GetItemIdByName("#WAKABA_ITEM_PENDANT")
wakaba.COLLECTIBLE_REVENGE_FRUIT = Isaac.GetItemIdByName("#WAKABA_ITEM_REVENGE_FRUIT")

wakaba.COLLECTIBLE_UNIFORM = Isaac.GetItemIdByName("#WAKABA_ITEM_UNIFORM")

wakaba.COLLECTIBLE_SECRET_CARD = Isaac.GetItemIdByName("#WAKABA_ITEM_SECRET_CARD")

wakaba.COLLECTIBLE_RETURN_POSTAGE = Isaac.GetItemIdByName("#WAKABA_ITEM_RETURN_POSTAGE")
wakaba.COLLECTIBLE_WAKABAS_BLESSING = Isaac.GetItemIdByName("#WAKABA_ITEM_BLESSING") -- Legacy
wakaba.COLLECTIBLE_BLESSING = Isaac.GetItemIdByName("#WAKABA_ITEM_BLESSING")

-- Items(T.Wakaba)

wakaba.COLLECTIBLE_BOOK_OF_FORGOTTEN = Isaac.GetItemIdByName("#WAKABA_ITEM_BOOK_OF_FORGOTTEN")
wakaba.COLLECTIBLE_EATHEART = Isaac.GetItemIdByName("#WAKABA_ITEM_EATHEART")
wakaba.COLLECTIBLE_WAKABAS_NEMESIS = Isaac.GetItemIdByName("#WAKABA_ITEM_NEMESIS") -- Legacy
wakaba.COLLECTIBLE_NEMESIS = Isaac.GetItemIdByName("#WAKABA_ITEM_NEMESIS")

-- Items(Shiori)
wakaba.COLLECTIBLE_BOOK_OF_FOCUS = Isaac.GetItemIdByName("#WAKABA_ITEM_BOOK_OF_FOCUS")
wakaba.COLLECTIBLE_DECK_OF_RUNES = Isaac.GetItemIdByName("#WAKABA_ITEM_BOTTLE_OF_RUNES")
wakaba.COLLECTIBLE_BOTTLE_OF_RUNES = Isaac.GetItemIdByName("#WAKABA_ITEM_BOTTLE_OF_RUNES")
wakaba.COLLECTIBLE_GRIMREAPER_DEFENDER = Isaac.GetItemIdByName("#WAKABA_ITEM_GRIMREAPER_DEFENDER")
wakaba.COLLECTIBLE_BOOK_OF_TRAUMA = Isaac.GetItemIdByName("#WAKABA_ITEM_BOOK_OF_TRAUMA")
wakaba.COLLECTIBLE_BOOK_OF_THE_FALLEN = Isaac.GetItemIdByName("#WAKABA_ITEM_BOOK_OF_THE_FALLEN")
wakaba.COLLECTIBLE_BOOK_OF_THE_GOD = Isaac.GetItemIdByName("#WAKABA_ITEM_BOOK_OF_THE_GOD")
wakaba.COLLECTIBLE_BOOK_OF_SILENCE = Isaac.GetItemIdByName("#WAKABA_ITEM_BOOK_OF_SILENCE")
wakaba.COLLECTIBLE_VINTAGE_THREAT = Isaac.GetItemIdByName("#WAKABA_ITEM_VINTAGE_THREAT")

wakaba.COLLECTIBLE_BOOK_OF_SHIORI = Isaac.GetItemIdByName("#WAKABA_ITEM_BOOK_OF_SHIORI")


-- Items(T.Shiori)

wakaba.COLLECTIBLE_BOOK_OF_CONQUEST = Isaac.GetItemIdByName("#WAKABA_ITEM_BOOK_OF_CONQUEST")
wakaba.COLLECTIBLE_MINERVA_AURA = Isaac.GetItemIdByName("#WAKABA_ITEM_MINERVA_AURA")
wakaba.COLLECTIBLE_MINERVA = Isaac.GetItemIdByName("#WAKABA_ITEM_MINERVA_AURA")

-- Items(Tsukasa)

wakaba.COLLECTIBLE_MURASAME = Isaac.GetItemIdByName("#WAKABA_ITEM_MURASAME")
wakaba.COLLECTIBLE_NASA_LOVER = Isaac.GetItemIdByName("#WAKABA_ITEM_NASA_LOVER")
wakaba.COLLECTIBLE_CONCENTRATION = Isaac.GetItemIdByName("#WAKABA_ITEM_CONCENTRATION")
wakaba.COLLECTIBLE_QUESTION_BLOCK = Isaac.GetItemIdByName("#WAKABA_ITEM_QUESTION_BLOCK")
wakaba.COLLECTIBLE_NEW_YEAR_BOMB = Isaac.GetItemIdByName("#WAKABA_ITEM_NEW_YEAR_EVE_BOMB")
wakaba.COLLECTIBLE_NEW_YEAR_EVE_BOMB = Isaac.GetItemIdByName("#WAKABA_ITEM_NEW_YEAR_EVE_BOMB")
wakaba.COLLECTIBLE_PHANTOM_CLOAK = Isaac.GetItemIdByName("#WAKABA_ITEM_PHANTOM_CLOAK")

wakaba.COLLECTIBLE_LUNAR_STONE = Isaac.GetItemIdByName("#WAKABA_ITEM_LUNAR_STONE")

-- Items(T.Tsukasa)

wakaba.COLLECTIBLE_FLASH_SHIFT = Isaac.GetItemIdByName("#WAKABA_ITEM_FLASH_SHIFT")
wakaba.COLLECTIBLE_ELIXIR_OF_LIFE = Isaac.GetItemIdByName("#WAKABA_ITEM_ELIXIR_OF_LIFE")

-- Items(Challenge)
wakaba.COLLECTIBLE_EYE_OF_CLOCK = Isaac.GetItemIdByName("#WAKABA_ITEM_EYE_OF_CLOCK")
wakaba.COLLECTIBLE_PLUMY = Isaac.GetItemIdByName("#WAKABA_ITEM_PLUMY")
wakaba.COLLECTIBLE_NEKO_FIGURE = Isaac.GetItemIdByName("#WAKABA_ITEM_NEKO_FIGURE")
wakaba.COLLECTIBLE_MICRO_DOPPELGANGER = Isaac.GetItemIdByName("#WAKABA_ITEM_MICRO_DOPPELGANGER")
wakaba.COLLECTIBLE_EXECUTIONER = Isaac.GetItemIdByName("#WAKABA_ITEM_EXECUTIONER")
wakaba.COLLECTIBLE_LIL_WAKABA = Isaac.GetItemIdByName("#WAKABA_ITEM_LIL_WAKABA")
wakaba.COLLECTIBLE_APOLLYON_CRISIS = Isaac.GetItemIdByName("#WAKABA_ITEM_APOLLYON_CRISIS")
wakaba.COLLECTIBLE_ISEKAI_DEFINITION = Isaac.GetItemIdByName("#WAKABA_ITEM_ISEKAI_DEFINITION")
wakaba.COLLECTIBLE_BALANCE = Isaac.GetItemIdByName("#WAKABA_ITEM_BALANCE")
wakaba.COLLECTIBLE_EDEN_STICKY_NOTE = Isaac.GetItemIdByName("#WAKABA_ITEM_EDEN_STICKY_NOTE")
wakaba.COLLECTIBLE_DOUBLE_DREAMS = Isaac.GetItemIdByName("#WAKABA_ITEM_DOUBLE_DREAMS")
