wakaba.PLAYER_WAKABA = Isaac.GetPlayerTypeByName("Wakaba", false)
wakaba.PLAYER_WAKABA_B = Isaac.GetPlayerTypeByName("WakabaB", true)
wakaba.PLAYER_SHIORI = Isaac.GetPlayerTypeByName("Shiori", false)
wakaba.PLAYER_SHIORI_B = Isaac.GetPlayerTypeByName("ShioriB", true)
wakaba.PLAYER_TSUKASA = Isaac.GetPlayerTypeByName("Tsukasa", false)
wakaba.PLAYER_TSUKASA_B = Isaac.GetPlayerTypeByName("TsukasaB", true)
--wakaba.PLAYER_RICHER = Isaac.GetPlayerTypeByName("Richer", false)
--wakaba.PLAYER_RICHER_B = Isaac.GetPlayerTypeByName("RicherB", true)
--[[ 
wakaba.PLAYER_WAKABA = Isaac.GetPlayerTypeByName("#WAKABA_WAKABA_NAME", false)
wakaba.PLAYER_WAKABA_B = Isaac.GetPlayerTypeByName("#WAKABA_WAKABAB_NAME", true)
wakaba.PLAYER_SHIORI = Isaac.GetPlayerTypeByName("#WAKABA_SHIORI_NAME", false)
wakaba.PLAYER_SHIORI_B = Isaac.GetPlayerTypeByName("#WAKABA_SHIORIB_NAME", true)
wakaba.PLAYER_TSUKASA = Isaac.GetPlayerTypeByName("#WAKABA_TSUKASA_NAME", false)
wakaba.PLAYER_TSUKASA_B = Isaac.GetPlayerTypeByName("#WAKABA_TSUKASAB_NAME", true)
 ]]