
wakaba.Enums.Trinkets.BITCOIN = Isaac.GetTrinketIdByName("#WAKABA_TRINKET_BITCOIN")
wakaba.Enums.Trinkets.CLOVER = Isaac.GetTrinketIdByName("#WAKABA_TRINKET_CLOVER")
wakaba.Enums.Trinkets.MAGNET_HEAVEN = Isaac.GetTrinketIdByName("#WAKABA_TRINKET_MAGNET_HEAVEN")
wakaba.Enums.Trinkets.HARD_BOOK = Isaac.GetTrinketIdByName("#WAKABA_TRINKET_HARD_BOOK")
wakaba.Enums.Trinkets.DETERMINATION_RIBBON = Isaac.GetTrinketIdByName("#WAKABA_TRINKET_DETERMINATION_RIBBON")
wakaba.Enums.Trinkets.BOOKMARK_BAG = Isaac.GetTrinketIdByName("#WAKABA_TRINKET_BOOKMARK_BAG")
wakaba.Enums.Trinkets.RING_OF_JUPITER = Isaac.GetTrinketIdByName("#WAKABA_TRINKET_RING_OF_JUPITER")
wakaba.Enums.Trinkets.DIMENSION_CUTTER = Isaac.GetTrinketIdByName("#WAKABA_TRINKET_DIMENSION_CUTTER")
wakaba.Enums.Trinkets.DELIMITER = Isaac.GetTrinketIdByName("#WAKABA_TRINKET_DELIMITER")
wakaba.Enums.Trinkets.RANGE_OS = Isaac.GetTrinketIdByName("#WAKABA_TRINKET_RANGE_OS")
wakaba.Enums.Trinkets.ISAAC_CARTRIDGE = Isaac.GetTrinketIdByName("#WAKABA_TRINKET_ISAAC_CARTRIDGE")
