
Activity.SetCharacterPortrait(wakaba.Enums.Players.WAKABA, "https://i.imgur.com/WxkeqiN.png")
Activity.SetCharacterPortrait(wakaba.Enums.Players.WAKABA_B, "https://i.imgur.com/pVJRzpU.png")
Activity.SetCharacterPortrait(wakaba.Enums.Players.SHIORI, "https://i.imgur.com/832MoU1.png")
Activity.SetCharacterPortrait(wakaba.Enums.Players.SHIORI_B, "https://i.imgur.com/S6Kw0xm.png")
Activity.SetCharacterPortrait(wakaba.Enums.Players.TSUKASA, "https://i.imgur.com/3KWZuSt.png")
Activity.SetCharacterPortrait(wakaba.Enums.Players.TSUKASA_B, "https://i.imgur.com/2ndmnN8.png")
Activity.SetCharacterPortrait(wakaba.Enums.Players.RICHER, "https://i.imgur.com/QeFv7eJ.png")
Activity.SetCharacterPortrait(wakaba.Enums.Players.RICHER_B, "https://i.imgur.com/QvV576P.png")
Activity.SetCharacterPortrait(wakaba.Enums.Players.RIRA, "https://i.imgur.com/tobYPVk.png")
