
-- Cards

wakaba.DESC_CARD_CRANE_CARD = Isaac.GetCardIdByName("#WAKABA_CARDDESC_CRANE_CARD")
wakaba.DESC_CARD_CONFESSIONAL_CARD = Isaac.GetCardIdByName("#WAKABA_CARDDESC_CONFESSIONAL_CARD")
wakaba.DESC_CARD_BLACK_JOKER = Isaac.GetCardIdByName("#WAKABA_CARDDESC_BLACK_JOKER")
wakaba.DESC_CARD_WHITE_JOKER = Isaac.GetCardIdByName("#WAKABA_CARDDESC_WHITE_JOKER")
wakaba.DESC_CARD_COLOR_JOKER = Isaac.GetCardIdByName("#WAKABA_CARDDESC_COLOR_JOKER")
wakaba.DESC_CARD_DREAM_CARD = Isaac.GetCardIdByName("#WAKABA_CARDDESC_DREAM_CARD")
wakaba.DESC_CARD_UNKNOWN_BOOKMARK = Isaac.GetCardIdByName("#WAKABA_CARDDESC_UNKNOWN_BOOKMARK")
wakaba.DESC_CARD_QUEEN_OF_SPADES = Isaac.GetCardIdByName("#WAKABA_CARDDESC_QUEEN_OF_SPADES")
wakaba.DESC_CARD_OLD_CARD = Isaac.GetCardIdByName("#WAKABA_CARDDESC_OLD_CARD")
wakaba.DESC_SOUL_WAKABA = Isaac.GetCardIdByName("#WAKABA_CARDDESC_SOUL_WAKABA")
wakaba.DESC_SOUL_SHIORI = Isaac.GetCardIdByName("#WAKABA_CARDDESC_SOUL_SHIORI")
wakaba.DESC_SOUL_TSUKASA = Isaac.GetCardIdByName("#WAKABA_CARDDESC_SOUL_TSUKASA")


-- Pills

wakaba.DESC_PILL_DAMAGE_MULTIPLIER_UP = Isaac.GetPillEffectByName("#WAKABA_PILLDESC_DAMAGE_MULTIPLIER_UP")
wakaba.DESC_PILL_DAMAGE_UP = Isaac.GetPillEffectByName("#WAKABA_PILLDESC_DAMAGE_UP")
wakaba.DESC_PILL_DAMAGE_DOWN = Isaac.GetPillEffectByName("#WAKABA_PILLDESC_DAMAGE_DOWN")
wakaba.DESC_PILL_ALL_STATS_UP = Isaac.GetPillEffectByName("#WAKABA_PILLDESC_ALL_STATS_UP")
wakaba.DESC_PILL_ALL_STATS_DOWN = Isaac.GetPillEffectByName("#WAKABA_PILLDESC_ALL_STATS_DOWN")
wakaba.DESC_PILL_TROLLED = Isaac.GetPillEffectByName("#WAKABA_PILLDESC_TROLLED")
wakaba.DESC_PILL_TO_THE_START = Isaac.GetPillEffectByName("#WAKABA_PILLDESC_TO_THE_START")
wakaba.DESC_PILL_EXPLOSIVE_DIARRHEA_2 = Isaac.GetPillEffectByName("#WAKABA_PILLDESC_EXPLOSIVE_DIARRHEA_2")
wakaba.DESC_PILL_SOCIAL_DISTANCE = Isaac.GetPillEffectByName("#WAKABA_PILLDESC_SOCIAL_DISTANCE")
wakaba.DESC_PILL_FIREY_TOUCH = Isaac.GetPillEffectByName("#WAKABA_PILLDESC_FIREY_TOUCH")