
-- Items(normal)

wakaba.DESC_COLLECTIBLE_MYSTERIOUS_GAME_CD =  Isaac.GetItemIdByName("#WAKABA_ITEMDESC_MYSTERIOUS_GAME_CD")
wakaba.DESC_COLLECTIBLE_WAKABA_DUALITY = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_DUALITY")
wakaba.DESC_COLLECTIBLE_D6_PLUS = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_D6_PLUS")
wakaba.DESC_COLLECTIBLE_D6_CHAOS = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_D6_CHAOS")
wakaba.DESC_COLLECTIBLE_LIL_MOE = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_LIL_MOE")
wakaba.DESC_COLLECTIBLE_LIL_SHIVA = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_LIL_SHIVA")
wakaba.DESC_COLLECTIBLE_MAIJIMA_MYTHOLOGY = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_MAIJIMA_MYTHOLOGY")
wakaba.DESC_COLLECTIBLE_DEJA_VU = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_DEJA_VU")
wakaba.DESC_COLLECTIBLE_MOE_MUFFIN = Isaac.GetItemIdByName("#WAKABA_MOE_MUFFIN")

-- Items(Wakaba)
wakaba.DESC_COLLECTIBLE_COUNTER = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_COUNTER")
wakaba.DESC_COLLECTIBLE_D_CUP_ICECREAM = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_D_CUP_ICECREAM")
wakaba.DESC_COLLECTIBLE_WAKABAS_PENDANT = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_PENDANT") -- Legacy
wakaba.DESC_COLLECTIBLE_PENDANT = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_PENDANT")
wakaba.DESC_COLLECTIBLE_REVENGE_FRUIT = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_REVENGE_FRUIT")

wakaba.DESC_COLLECTIBLE_UNIFORM = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_UNIFORM")

wakaba.DESC_COLLECTIBLE_SECRET_CARD = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_SECRET_CARD")

wakaba.DESC_COLLECTIBLE_RETURN_POSTAGE = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_RETURN_POSTAGE")
wakaba.DESC_COLLECTIBLE_WAKABAS_BLESSING = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_BLESSING") -- Legacy
wakaba.DESC_COLLECTIBLE_BLESSING = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_BLESSING")

-- Items(T.Wakaba)

wakaba.DESC_COLLECTIBLE_BOOK_OF_FORGOTTEN = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_BOOK_OF_FORGOTTEN")
wakaba.DESC_COLLECTIBLE_EATHEART = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_EATHEART")
wakaba.DESC_COLLECTIBLE_WAKABAS_NEMESIS = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_NEMESIS") -- Legacy
wakaba.DESC_COLLECTIBLE_NEMESIS = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_NEMESIS")

-- Items(Shiori)
wakaba.DESC_COLLECTIBLE_BOOK_OF_FOCUS = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_BOOK_OF_FOCUS")
wakaba.DESC_COLLECTIBLE_DECK_OF_RUNES = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_BOTTLE_OF_RUNES")
wakaba.DESC_COLLECTIBLE_BOTTLE_OF_RUNES = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_BOTTLE_OF_RUNES")
wakaba.DESC_COLLECTIBLE_GRIMREAPER_DEFENDER = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_GRIMREAPER_DEFENDER")
wakaba.DESC_COLLECTIBLE_BOOK_OF_TRAUMA = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_BOOK_OF_TRAUMA")
wakaba.DESC_COLLECTIBLE_BOOK_OF_THE_FALLEN = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_BOOK_OF_THE_FALLEN")
wakaba.DESC_COLLECTIBLE_BOOK_OF_THE_GOD = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_BOOK_OF_THE_GOD")
wakaba.DESC_COLLECTIBLE_BOOK_OF_SILENCE = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_BOOK_OF_SILENCE")
wakaba.DESC_COLLECTIBLE_VINTAGE_THREAT = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_VINTAGE_THREAT")

wakaba.DESC_COLLECTIBLE_BOOK_OF_SHIORI = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_BOOK_OF_SHIORI")


-- Items(T.Shiori)

wakaba.DESC_COLLECTIBLE_BOOK_OF_CONQUEST = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_BOOK_OF_CONQUEST")
wakaba.DESC_COLLECTIBLE_MINERVA_AURA = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_MINERVA_AURA")
wakaba.DESC_COLLECTIBLE_MINERVA = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_MINERVA_AURA")

-- Items(Tsukasa)

wakaba.DESC_COLLECTIBLE_MURASAME = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_MURASAME")
wakaba.DESC_COLLECTIBLE_NASA_LOVER = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_NASA_LOVER")
wakaba.DESC_COLLECTIBLE_CONCENTRATION = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_CONCENTRATION")
wakaba.DESC_COLLECTIBLE_QUESTION_BLOCK = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_QUESTION_BLOCK")
wakaba.DESC_COLLECTIBLE_NEW_YEAR_BOMB = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_NEW_YEAR_EVE_BOMB")
wakaba.DESC_COLLECTIBLE_NEW_YEAR_EVE_BOMB = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_NEW_YEAR_EVE_BOMB")
wakaba.DESC_COLLECTIBLE_PHANTOM_CLOAK = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_PHANTOM_CLOAK")

wakaba.DESC_COLLECTIBLE_LUNAR_STONE = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_LUNAR_STONE")

-- Items(T.Tsukasa)

wakaba.DESC_COLLECTIBLE_FLASH_SHIFT = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_FLASH_SHIFT")
wakaba.DESC_COLLECTIBLE_ELIXIR_OF_LIFE = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_ELIXIR_OF_LIFE")

-- Items(Challenge)
wakaba.DESC_COLLECTIBLE_EYE_OF_CLOCK = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_EYE_OF_CLOCK")
wakaba.DESC_COLLECTIBLE_PLUMY = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_PLUMY")
wakaba.DESC_COLLECTIBLE_NEKO_FIGURE = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_NEKO_FIGURE")
wakaba.DESC_COLLECTIBLE_MICRO_DOPPELGANGER = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_MICRO_DOPPELGANGER")
wakaba.DESC_COLLECTIBLE_EXECUTIONER = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_EXECUTIONER")
wakaba.DESC_COLLECTIBLE_LIL_WAKABA = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_LIL_WAKABA")
wakaba.DESC_COLLECTIBLE_APOLLYON_CRISIS = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_APOLLYON_CRISIS")
wakaba.DESC_COLLECTIBLE_ISEKAI_DEFINITION = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_ISEKAI_DEFINITION")
wakaba.DESC_COLLECTIBLE_BALANCE = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_BALANCE")
wakaba.DESC_COLLECTIBLE_STICKY_NOTE = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_STICKY_NOTE")
wakaba.DESC_COLLECTIBLE_DOUBLE_DREAMS = Isaac.GetItemIdByName("#WAKABA_ITEMDESC_DOUBLE_DREAMS")
